### PR TITLE
Echo instructions

### PR DESCRIPTION
**Pull request by Benedict-Carling**
## Adds new method to Basic build to export 2 CSVS with Echo Instructions as a Zip

Contains 4 arguments as below.

- Path to specify output path to zip file
- bufferWell to state location in 6 well plate of Assembly Buffer
- waterWell to state location in 6 well plate of dH2O
- alternate_well to state whether alternating wells are used in 384 source plate

```python
export_echo_assembly(
        path: str = None,
        bufferWell: str = "A1",
        waterWell: str = "B1",
        alternate_well: bool = False,
    )
```
Raises Value Errors with Error Messages is 4 different situations.

- BufferWell is not in `["A1", "B1", "A2", "B2", "A3", "B3"]`
- waterWell is not in `["A1", "B1", "A2", "B2", "A3", "B3"]`
- `len(self.basic_assemblies) >= 96`, as output plate is 96 well plate
- source wells used is equal or more than 384 for `alternate_well(False)`, 192 for `alternate_well(True)`, this takes into account whether multiple wells are used for single clips

## Example Usage and Outputs

```python
build = bsb.BasicBuild(
    bsb.BasicAssembly(
        "First_Assembly_With_18",
        bsb.BASIC_SEVA_PARTS["v0.1"]["18"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMP"],
        bsb.BASIC_CDS_PARTS["v0.1"]["sfGFP"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMS"],
    ),
    bsb.BasicAssembly(
        "Second_Assembly_With_26",
        bsb.BASIC_SEVA_PARTS["v0.1"]["26"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMP"],
        bsb.BASIC_CDS_PARTS["v0.1"]["sfGFP"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMS"],
    ),
)
build.export_echo_assembly()
```
outputs
> [Echo_Output_SmallBuild.zip](https://github.com/LondonBiofoundry/basicsynbio/files/5965011/Echo_Output_SmallBuild.zip)

```python
build = bsb.BasicBuild(
    bsb.BasicAssembly(
        "First_Assembly_With_18",
        bsb.BASIC_SEVA_PARTS["v0.1"]["18"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMP"],
        bsb.BASIC_CDS_PARTS["v0.1"]["sfGFP"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMS"],
    ),
    bsb.BasicAssembly(
        "Second_Assembly_With_26",
        bsb.BASIC_SEVA_PARTS["v0.1"]["26"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMP"],
        bsb.BASIC_CDS_PARTS["v0.1"]["sfGFP"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMS"],
    ),
)

echopath = build.export_echo_assembly(alternate_well=True)
```

outputs
> [small_alternatewellsTrue.zip](https://github.com/LondonBiofoundry/basicsynbio/files/5965047/small_alternatewellsTrue.zip)

```python
promoter_assemblies = []
promoter_assemblies += [
    bsb.BasicAssembly(
        f"promoter_construct_{ind}",
        bsb.BASIC_SEVA_PARTS["v0.1"]["26"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMP"],
        promoter,
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["UTR1-RBS1"],
        bsb.BASIC_CDS_PARTS["v0.1"]["sfGFP"],
        bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMS"],
    )
    for ind, promoter in enumerate(bsb.BASIC_PROMOTER_PARTS["v0.1"].values())
]

build = bsb.BasicBuild(*promoter_assemblies)

build.export_echo_assembly()
```

outputs
>[Echo_AllPromoters.zip](https://github.com/LondonBiofoundry/basicsynbio/files/5965048/Echo_AllPromoters.zip)

Unit-tests are written for each Value error and to ensure values that I have predicted definitely needs checking if output files are okay.

### CODE REVIEW

**Review by hainesm6 — COMMENTED** [review]
I think a better solution to this is to have seperate objects that process a BasicBuild object and return/generate data within an `automate` module.

**Comment by Benedict-Carling** [comment]
Hi @hainesm6 this pull request is ready to be checked again, whenever your free or we can talk about it on Wednesday!

Changes

- Moves the function to its own module outside of cam
- removes clip_index_origin_mapping object, now no variables/objects are hanging within the function, this could be done with the addition of Plate class from plate map
- adds functionality for more than 96 assemblies, limiting factor is 384 clip wells filled if alternate_wells = false and 192 for true, when there are more than 96 assemblies 2 CSVS (clips, water buffer) are created for each 96 assemblies set with the final set being equal or less that 96 assemblies.

an example with 189 assemblies:
```python
utr_linkers = ["UTR1-RBS1", "UTR1-RBS2", "UTR1-RBS3"]
promoter_assemblies = []
for utr_linker in utr_linkers:
    promoter_assemblies += [
        bsb.BasicAssembly(
            f"promoter_construct_{ind}_{utr_linker}",
            bsb.BASIC_SEVA_PARTS["v0.1"]["26"],
            bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMP"],
            promoter,
            bsb.BASIC_BIOLEGIO_LINKERS["v0.1"][utr_linker],
            bsb.BASIC_CDS_PARTS["v0.1"]["sfGFP"],
            bsb.BASIC_BIOLEGIO_LINKERS["v0.1"]["LMS"],
        )
        for ind, promoter in enumerate(bsb.BASIC_PROMOTER_PARTS["v0.1"].values())
    ]
build = bsb.BasicBuild(*promoter_assemblies)
bsb.export_echo_assembly(build)
```

[Echo_Instructions_22-02-2021_14.04.34.zip](https://github.com/LondonBiofoundry/basicsynbio/files/6023254/Echo_Instructions_22-02-2021_14.04.34.zip)

**Comment by hainesm6** [comment]
Really great work @Benedict-Carling 🥇 Only thing I noticed was mixed case useage in some of the variable names. Otherwise it's ready to go!

**Comment by Benedict-Carling** [comment]
Thanks @hainesm6 🎉 this latest version, runs git pull origin master, and changes all instances of bufferWell and waterWell to buffer_well and water_well

**Pull request merged**
